Lab:
	g++ -c -g makeTree.cpp -o makeTree.o
	g++ -c -g journey.cpp -o journey.o
	g++ -c -g sort.cpp -o sort.o
	g++ -c -g tree.cpp -o tree.o
	g++ -c -g choose.cpp -o choose.o
	g++ -g makeTree.o journey.o sort.o tree.o choose.o -o makeTree
	rm makeTree.o journey.o sort.o tree.o choose.o
